<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.picketlink</groupId>
    <artifactId>picketlink-parent</artifactId>
    <version>2.5.5.jdk17.1</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <artifactId>picketlink-idm-parent</artifactId>
  <packaging>pom</packaging>

  <name>PicketLink IDM Parent</name>

  <properties>
    <jboss.logging.version>3.5.3.Final</jboss.logging.version>
    <jboss.logging.processor.version>3.0.4.Final</jboss.logging.processor.version>
  </properties>

  <modules>
    <module>api</module>
    <module>impl</module>
    <module>simple-schema</module>
    <module>tests</module>
    <module>drools</module>
    <module>admin</module>
  </modules>

  <dependencies>
    <dependency>
      <groupId>org.jboss.logging</groupId>
      <artifactId>jboss-logging-processor</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.jboss.logging</groupId>
      <artifactId>jboss-logging-annotations</artifactId>
      <version>${jboss.logging.processor.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.jboss.logging</groupId>
      <artifactId>jboss-logging</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>org.jboss.logging</groupId>
              <artifactId>jboss-logging-processor</artifactId>
              <version>${jboss.logging.processor.version}</version>
            </path>
            <path>
              <groupId>org.jboss.logging</groupId>
              <artifactId>jboss-logging-annotations</artifactId>
              <version>${jboss.logging.processor.version}</version>
            </path>
            <path>
              <groupId>org.jboss.logging</groupId>
              <artifactId>jboss-logging</artifactId>
              <version>${jboss.logging.version}</version>
            </path>
            <path>
              <groupId>org.jboss.jdeparser</groupId>
              <artifactId>jdeparser</artifactId>
              <version>2.0.3.Final</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-checkstyle-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

</project>
